# Generated by Django 3.2.9 on 2021-11-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211121_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='pathogen',
            field=models.CharField(default='ccc', max_length=255),
            preserve_default=False,
        ),
    ]
